# NumPy for AI/ML
## Conceptual & Technical Assessment



# Aim

To assess students’ ability to explain, implement, interpret, debug and apply NumPy concepts in AI/ML-oriented data and modelling tasks.
# Learning Outcomes

By the end of the assignment, students will be able to:

- Explain core NumPy concepts and justify when they are used.
- Construct vectorized NumPy solutions for numerical problems.
- Interpret array shapes, indexing, broadcasting and aggregation results.
- Analyse and resolve implementation errors and edge cases.
- Apply NumPy operations in preprocessing, image and simple modelling scenarios.

# Section A – Conceptual Understanding

**Total Marks: 20**

This section focuses on understanding the fundamental NumPy concepts and their applications in AI/ML. The answers are written in simple and clear terms, with relevant examples where useful.

## A1. NumPy Arrays vs Python Lists

**Question:**  
Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons. **[2 marks]**

**Answer:**  
NumPy arrays are generally preferred over Python lists for **numerical computation** because they support **vectorized operations**, which allow calculations to be performed on an entire array at once. They are also designed for **efficient numerical processing** and provide useful built-in **mathematical and statistical functions**.

**Two Concrete Reasons:**  
1. **Vectorized Operations:** NumPy can perform calculations on many values at once without using explicit Python loops.  
2. **Built-in Numerical Functions:** NumPy provides functions such as `mean()`, `max()`, `min()`, and `std()` for common mathematical and statistical operations.

These features make NumPy arrays useful for handling large datasets in **AI/ML workloads**.

**Example:**  
In image processing, thousands of pixel values can be stored in a NumPy array and processed together instead of handling each pixel separately.

**Key Points:**  
- Efficient numerical computation
- Vectorized operations
- Built-in mathematical and statistical functions
- Useful for AI/ML workloads

## A2. Vectorization

**Question:**  
Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets? **[2 marks]**

**Answer:**  
**Vectorization** means performing an operation on an entire NumPy array at once instead of processing each element using an explicit Python loop. Replacing a Python loop with a vectorized NumPy operation can make numerical computations more efficient, especially when working with **large datasets**. It also makes the code shorter, simpler, and easier to read. Therefore, vectorization is an important technique for efficient numerical processing in **AI/ML**.

**Example:**  
Suppose we want to add 10 to every value in an array:

```python
marks = np.array([60, 70, 80, 90])
result = marks + 10



## A3. Element-wise Multiplication vs Matrix Multiplication

**Question:**  
For compatible 2D arrays A and B, explain `A * B` vs `A @ B`. Describe one neural-network situation for each. **[2 marks]**

**Answer:**  
- For compatible 2D NumPy arrays, `A * B` performs **element-wise multiplication**, meaning each element of A is multiplied by the corresponding element of B.In contrast, `A @ B` performs **matrix multiplication**, where rows of A are multiplied with columns of B.
- In a neural network, element-wise multiplication can be used for **scaling values or applying masks**, while matrix multiplication is commonly used to calculate the **weighted sum of inputs using weights**. Therefore, `A * B` and `A @ B` perform different types of multiplication.

**Example:**
```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A * B)
print(A @ B)

## A4. Broadcasting

**Question:**  
What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise. **[2 marks]**

**Answer:**  
**Broadcasting** is a NumPy feature that allows arrays with different shapes to be used together in **element-wise operations**, when their shapes are compatible.

**General Rule:**

- **Same dimension:** Two dimensions are compatible if they are equal.  
  Example: `3` and `3` → compatible.

- **One dimension is 1:** Two dimensions are also compatible if one of them is `1`.  
  Example: `3` and `1` → compatible.

NumPy compares the dimensions from **right to left**. If every pair of dimensions satisfies one of these conditions, broadcasting is possible. Otherwise, NumPy cannot perform the element-wise operation.

**Example:**
```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

result = A + B





## A5. `flatten()` vs `ravel()`

**Question:**  
What is the difference between `flatten()` and `ravel()`? If you are working with large images and memory is constrained, which would you prefer and why? **[2 marks]**

**Answer:**  
Both `flatten()` and `ravel()` convert a multi-dimensional NumPy array into a **one-dimensional array**, but they handle memory differently.

- **`flatten()`** → Always creates a **copy** of the original array, so it uses additional memory.

- **`ravel()`** → Usually returns a **view** of the original array when possible, so it generally uses less additional memory.

For example, if a large image takes 500 MB of memory, using `flatten()` may require another 500 MB for the copied array. However, `ravel()` can usually work with the existing data without creating another 500 MB copy.

Therefore, when working with **large images and limited memory, `ravel()` is preferred because it can avoid creating an unnecessary copy and reduce additional memory usage.**

**Example:**
```python
image = np.array([[1, 2],
                  [3, 4]])

flat_image = image.flatten()
ravel_image = image.ravel()

print(flat_image)
print(ravel_image)

## A6. `axis=0` vs `axis=1`

**Question:**  
Explain what `axis=0` and `axis=1` mean in aggregation operations. Give a small example. 


**Answer:**  
In NumPy, the `axis` parameter tells the aggregation function **along which direction the operation should be performed**.

- **`axis=0`** → Performs the operation **down the rows**, so we get a result for each **column**.

- **`axis=1`** → Performs the operation **across the columns**, so we get a result for each **row**.

**Example:**
```python 
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.sum(A, axis=0))
print(np.sum(A, axis=1))

**Output:**
Sum with axis=0: [5 7 9]
Sum with axis=1: [ 6 15]


## A7. Normalization vs Standardization

**Question:**  
What is normalization vs standardization? Why do we apply them before ML? 

**Answer:**  
**Normalization** and **standardization** are data preprocessing techniques used to bring numerical features to a suitable scale before applying Machine Learning (ML) algorithms.

- **Normalization:** Rescales values to a fixed range, commonly **0 to 1**.
- **Standardization:** Transforms the data so that it has a **mean of 0** and a **standard deviation of 1**.

We apply them before ML because different features may have different numerical scales. Scaling the features helps prevent large-valued features from having an unwanted influence and can help some ML algorithms perform more effectively.

**Example:**  
Suppose a dataset contains:

```text
Age:     18 – 60
Salary:  20,000 – 1,00,000

## A8. `nanmean()` vs `mean()`

**Question:**  
What does `np.nanmean()` do that `np.mean()` does not when the array contains NaN? **[2 marks]**

**Answer:**  
`NaN` means **Not a Number** and is commonly used to represent a missing or unavailable numerical value.

- **`np.mean()`** calculates the average of the values, but if the array contains a `NaN`, the result is usually also `NaN`.
- **`np.nanmean()`** calculates the average while **ignoring the `NaN` values**.

Therefore, `np.nanmean()` is useful when we want to calculate the average of available values without letting missing values make the result `NaN`.

**Example:**

```python
data = np.array([10, 20, np.nan, 40])

print("Mean:", np.mean(data))
print("NaN Mean:", np.nanmean(data))
```


**Output:**
Mean: nan
NaN Mean: 23.333333333333332



## A9. Shape of Image Data

**Question:**  
In ML convention, if `X.shape = (samples, features)`, what is the exact shape if you have 64 RGB images of size 128×128? **[2 marks]**

**Answer:**  
For an RGB image, each pixel has **3 color channels**: Red, Green, and Blue.

Each image has:

```text
128 × 128 × 3

## A10. Reproducibility

**Question:**  
What is reproducibility in ML experiments? Why is setting a random seed important? Show how you would fix the seed in NumPy. **[2 marks]**

**Answer:**  

**Reproducibility** means getting the same or consistent results when an ML experiment is run again using the same data, code, and settings.

Many ML and data-processing operations involve **randomness**, such as generating random values, initializing model parameters, or selecting random samples. If the random values change every time we run the program, the results may also change.

Setting a **random seed** fixes the starting point of the random number generator. This makes the generated random values repeatable, which helps us **debug, test, compare, and reproduce** ML experiments.

**Example:**
```python
rng = np.random.default_rng(42)
print(rng.random(3))
```
**Output:**
[0.77395605 0.43887844 0.85859792]

# Section B – Predict the Output

**Total Marks: 16**

This section focuses on predicting NumPy outputs and shapes by understanding array operations, broadcasting, indexing, and matrix operations.

## B1. Predict the Output and/or Shape

**Question:**  
Predict the exact output and/or resulting shape. Justify in one sentence. **[2 marks]**
```text
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)
```
***Predicted Outout:***
(3, 3)

In [1]:

#Checking the actual output by executing the program
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

(3, 3)


**B1.One-line Justification:**  
The arrays have shapes `(3,)` and `(3, 1)`, so NumPy broadcasting produces a resulting shape of `(3, 3)`.

## B2. Predict the Output and/or Shape

**Question:**  
Predict the exact output and/or resulting shape. **[2 marks]**
**Given code**
```python
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])
```

**Predicted Output:**
```
[2 5]
```


In [2]:
#Checking the actual output by executing the program
import numpy as np

x = np.arange(1, 7).reshape(2, 3)

print(x[:, 1])

[2 5]


**B2.One-line Justification:**  
`x[:, 1]` selects all rows from the second column, resulting in the values `[2, 5]`.

## B3. Predict the Output

**Question:**  
Predict the exact output of the following NumPy code. **[2 marks]**

**Given Code:**
```python
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])
```
**Predicted Output:**
```
[10 20]
```



In [3]:
arr = np.array([5, 10, 15, 20, 25])

print(arr[arr % 10 == 0])

[10 20]


**B3.One-line Justification:**  
The condition `arr % 10 == 0` selects the elements that are exactly divisible by 10, giving `[10 20]`.

## B4. Predict the Output

**Question:**  
Predict the exact output of the following NumPy code. **[2 marks]**

**Given Code:**
```python
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)
```
**Predicted Output:**
```
[[10 14]
 [14 20]]
```



In [4]:
m = np.array([[1, 2], [3, 4]])

print(m.T @ m)

[[10 14]
 [14 20]]


**B4.One-line Justification:**  
`m.T @ m` first transposes the matrix and then performs matrix multiplication, producing `[[10 14], [14 20]]`.

## B5. Predict the Output

**Question:**  
Predict the exact output of the following NumPy code. **[2 marks]**

**Given Code:**
```python
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))
```
**Predicted Output:**
```
nan 2.3333333333333335
```



In [5]:
data = np.array([1, 2, np.nan, 4])

print(np.mean(data), np.nanmean(data))

nan 2.3333333333333335


**B5.One-line Justification:**  
`np.mean()` returns `nan` because the array contains a NaN value, while `np.nanmean()` ignores the NaN and calculates the mean of the remaining values.

## B6. Predict the Output

**Question:**  
Predict the exact output of the following NumPy code. **[2 marks]**

**Given Code:**
```python
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)
```
**Predicted Output:**
```
[0 1 1]
```



In [6]:
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

[0 1 1]


**B6.One-line Justification:**  
`np.where()` assigns `1` to values greater than 15 and `0` to the remaining values, giving `[0 1 1]`.

## B7. Predict the Output

**Question:**  
Predict the exact output of the following NumPy code. **[2 marks]**

**Given Code:**
```python
a = np.zeros((3, 4))
print(a.ndim, a.size)
```
**Predicted Output:**
```
2 12
```



In [7]:
a = np.zeros((3, 4))
print(a.ndim, a.size)

2 12


**B7.One-line Justification:**  
The array has 2 dimensions and contains `3 × 4 = 12` elements, so `a.ndim` is `2` and `a.size` is `12`.

## B8. Predict the Output

**Question:**  
Predict the exact output of the following NumPy code. **[2 marks]**

**Given Code:**
```python
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])
```
**Predicted Output:**
```
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
```



In [8]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


**B8.One-line Justification:**  
`[::-1, ::-1]` reverses both the rows and columns of the array, producing the elements in reverse order.

# Section C – Coding / Implementation

**Total Marks: 40**

This section focuses on implementing NumPy operations using vectorized code for numerical computation, preprocessing, and AI/ML tasks.

## C1. Exam Score Classification

**Question:**  
Given a 1D NumPy array of exam scores, use `np.where()` to produce labels `'P'` (score >= 40) or `'F'` (score < 40). **[5 marks]**

In [9]:
# Program: Classify exam scores as Pass (P) or Fail (F) using NumPy

import numpy as np

# Create a 1D array of exam scores
scores = np.array([35, 42, 78, 25, 60, 39, 90])

# Assign P for scores >= 40 and F for scores < 40
labels = np.where(scores >= 40, "P", "F")

# Display the result
print(labels)

['F' 'P' 'P' 'F' 'P' 'F' 'P']


### C1.One-line Justification:

`np.where()` checks the condition `scores >= 40` for every element in the array. If the condition is True, it assigns `"P"`; otherwise, it assigns `"F"`. This allows all exam scores to be classified at once without using an explicit loop.

## C2. Standardize a 1D NumPy Array

**Question:**  
Write a function `standardize(x)` that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. **[5 marks]**

In [10]:
# Program: Standardize a 1D NumPy array using Z-score standardization
# Define a function to standardize the input array
def standardize(x):
    # Calculate the mean of the array
    mean = np.mean(x)
    # Calculate the standard deviation of the array
    std = np.std(x)
    # Apply the Z-score formula
    return (x - mean) / std
# Create a sample 1D NumPy array
scores = np.array([10, 20, 30, 40, 50])
# Standardize the scores
standardized_scores = standardize(scores)
# Display the result
print(standardized_scores)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### C2.Justification:

The `standardize()` function converts the values into Z-scores using the formula `(x - mean) / standard deviation`. First, `np.mean()` calculates the average value and `np.std()` calculates the standard deviation. Then, the formula is applied to every element of the array using NumPy vectorization, so no explicit loop is required.

## C3. Combine Two 2D Arrays

**Question:**  
Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using the appropriate stacking function and print the resulting shape. **[5 marks]**

In [11]:
# Program: Combine two batches of data using vertical stacking
# Create the first batch with 2 samples and 3 features
batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Create the second batch with 2 samples and 3 features
batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
# Combine both batches row-wise
combined = np.vstack((batch1, batch2))
# Display the combined array
print(combined)
# Display the shape of the combined array
print("Shape:", combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)


### C3. Justification

`np.vstack()` combines the two arrays vertically, meaning the rows of `batch2` are added below the rows of `batch1`. Since both batches have the same number of features (3 columns), they can be stacked successfully. The resulting array contains 4 samples and 3 features, so its shape is `(4, 3)`.

## C4. Standardize a Dataset Column-Wise

**Question:**  
Given `X` with shape `(100, 5)`, compute the column-wise mean and standard deviation, and standardize `X` in one vectorized expression. **[5 marks]**

In [22]:
# Program: Compute column-wise mean and standard deviation and standardize the dataset
# Create a sample dataset with 100 samples and 5 features
X = np.random.default_rng(42).normal(size=(100, 5))

# Calculate the mean and standard deviation for each column
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
# Standardize all columns using one vectorized expression
X_standardized = (X - mean) / std

# Display the shapes
print("Original shape:", X.shape)
print("Mean shape:", mean.shape)
print("Standardized shape:", X_standardized.shape)

Original shape: (100, 5)
Mean shape: (5,)
Standardized shape: (100, 5)


### C4.Justification

`axis=0` calculates the mean and standard deviation separately for each of the 5 columns. The expression `(X - mean) / std` uses NumPy broadcasting to standardize all 100 samples and 5 features at once. Therefore, the standardized dataset keeps the original shape `(100, 5)` without using an explicit loop.

## C5. Linear Model Prediction and MSE
**Question:**  
Given input data `X`, weights `w`, bias `b`, and true values `y_true`, implement the prediction equation `y_pred = X @ w + b` and compute the Mean Squared Error (MSE) using `y_true`. **[5 marks]**

In [13]:
# Program: Calculate linear model predictions and Mean Squared Error
# Create input data with 3 samples and 2 features
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

# Define the weight values for the two features
w = np.array([0.5, 1.0])
# Define the bias value
b = 2.0

# Calculate predictions using matrix multiplication
y_pred = X @ w + b

# Define the actual target values
y_true = np.array([4, 5, 6])

# Calculate Mean Squared Error
mse = np.mean((y_true - y_pred) ** 2)

# Display the predictions
print("Predictions:", y_pred)
# Display the Mean Squared Error
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 1.1666666666666667


### C5.Justification
`X @ w + b` calculates the predicted values using matrix multiplication and bias. MSE is the average of the squared differences between the actual and predicted values.

## C6. Generate Reproducible Random Data

**Question:**  
Using `np.random.default_rng()` with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed. **[5 marks]**

In [14]:
# Program: Generate reproducible random data using a fixed seed
# Create a random number generator with seed 42
rng1 = np.random.default_rng(42)
# Generate 10 samples and 3 features from a normal distribution
data1 = rng1.normal(size=(10, 3))

# Create another random number generator with the same seed
rng2 = np.random.default_rng(42)
# Generate another set using the same seed
data2 = rng2.normal(size=(10, 3))

# Print the shape of the generated data
print("Shape:", data1.shape)

# Check whether both results are identical
print("Identical results:", np.array_equal(data1, data2))

Shape: (10, 3)
Identical results: True


### C6.Justification

`np.random.default_rng(42)` creates a random number generator using the fixed seed `42`. The `normal()` function generates random values from a normal distribution, with `size=(10, 3)` creating 10 samples and 3 features. When the same seed is used again, NumPy generates the same values, so `np.array_equal()` returns `True`. The resulting data has a shape of `(10, 3)`.

## C7. Normalize a Grayscale Image

**Question:**  
Given a grayscale image represented as a 2D NumPy array with pixel values in the range `[0, 255]`, apply min-max normalization to scale the values to the range `[0, 1]`. **[5 marks]**

In [15]:
# Program: Normalize grayscale image pixel values to the range [0, 1]
# Create a sample grayscale image with pixel values from 0 to 255
image = np.array([[0, 50, 100],
                  [150, 200, 250],
                  [25, 125, 255]])

# Find the minimum pixel value
min_value = np.min(image)

# Find the maximum pixel value
max_value = np.max(image)

# Apply min-max normalization
normalized_image = (image - min_value) / (max_value - min_value)

# Display the original image
print("Original Image:")
print(image)

# Display the normalized image
print("\nNormalized Image:")
print(normalized_image)
# Display the minimum and maximum normalized values
print("\nMinimum:", np.min(normalized_image))
print("Maximum:", np.max(normalized_image))

Original Image:
[[  0  50 100]
 [150 200 250]
 [ 25 125 255]]

Normalized Image:
[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 0.98039216]
 [0.09803922 0.49019608 1.        ]]

Minimum: 0.0
Maximum: 1.0


### C7.Justification

Min-max normalization transforms the pixel values from their original range `[0, 255]` into the range `[0, 1]`. The formula `(image - min_value) / (max_value - min_value)` subtracts the minimum value and divides by the range of values. This is useful in machine learning and image processing because normalized values are easier for models to process.

## C8. Calculate Average Pixel Value for Each Image

**Question:**  
Given 4 RGB images with shape `(4, 28, 28, 3)`, compute the average pixel value of each image across height, width, and channels. State the axis used and explain why. **[5 marks]**

In [16]:
# Program: Calculate the average pixel value of each RGB image
# Create a batch of 4 RGB images with height 28, width 28, and 3 color channels
images = np.random.default_rng(42).integers(
    0, 256, size=(4, 28, 28, 3)
)
# Calculate the average pixel value for each image
average_pixels = np.mean(images, axis=(1, 2, 3))

# Display the shape of the image batch
print("Image batch shape:", images.shape)

# Display the average pixel value of each image
print("Average pixel values:", average_pixels)

# Display the shape of the result
print("Result shape:", average_pixels.shape)

Image batch shape: (4, 28, 28, 3)
Average pixel values: [127.56505102 126.25212585 125.75722789 126.9914966 ]
Result shape: (4,)


### C8.Justification

The image batch has the shape `(4, 28, 28, 3)`, where 4 represents the number of images, 28 and 28 represent height and width, and 3 represents the RGB channels. We use `axis=(1, 2, 3)` to calculate the mean across the height, width, and color channels while keeping each image separate. Therefore, the result has shape `(4,)`, containing one average pixel value for each image.

# Section D – Applied NumPy Tasks

**Total Marks: 24**

This section focuses on applying NumPy concepts to practical data preprocessing, image processing, and debugging tasks.

## D1. Data Preprocessing Pipeline

**Question:**  
Given a raw 1D or 2D NumPy array containing `NaN` values, describe and implement a step-by-step preprocessing pipeline to:

1. Detect missing values.
2. Handle the missing values appropriately and justify the chosen strategy.
3. Normalize or standardize the cleaned data before using it in a model.

Implement the complete pipeline using a sample NumPy array containing at least one `NaN` value. **[8 marks]**

In [17]:
# Program: Detect, handle, and standardize missing values in a NumPy array
# Create a sample dataset containing NaN values
data = np.array([10.0, 20.0, np.nan, 40.0, 50.0, np.nan])

# Step 1: Detect missing values
missing_values = np.isnan(data)

# Display the positions of missing values
print("Missing value positions:", missing_values)

# Count the total number of missing values
print("Number of missing values:", np.sum(missing_values))

# Step 2: Replace NaN values with the mean of the available values
mean_value = np.nanmean(data)
cleaned_data = np.where(
    np.isnan(data),
    mean_value,
    data
)
# Display the cleaned data
print("Cleaned data:", cleaned_data)

# Step 3: Standardize the cleaned data
mean = np.mean(cleaned_data)
std = np.std(cleaned_data)
standardized_data = (cleaned_data - mean) / std
# Display the standardized data
print("Standardized data:", standardized_data)

Missing value positions: [False False  True False False  True]
Number of missing values: 2
Cleaned data: [10. 20. 30. 40. 50. 30.]
Standardized data: [-1.54919334 -0.77459667  0.          0.77459667  1.54919334  0.        ]


### D1.Justification

The preprocessing pipeline first uses `np.isnan()` to detect the missing values in the dataset. The missing values are replaced with the mean of the available values using `np.nanmean()`, because removing samples is unnecessary for this small dataset and mean imputation keeps all the data points. After handling the missing values, the cleaned data is standardized using the Z-score formula so that the values are centered around 0 with a standard deviation of 1. This preprocessing makes the data more suitable for many machine learning models.

## D2. Image Batch Understanding

**Question:**  
 D2. Image Batch Understanding [8 marks]
 
 1.Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.
 
2.Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.
 
 3.Compute the average image of the batch, meaning the element-wise mean across all 16 images.
 
 4.State the shape of your result and explain why.
 

In [18]:
# Program: Create an RGB image batch and calculate the average image
# Create a random number generator with a fixed seed
rng = np.random.default_rng(42)

# Create a batch of 16 RGB images of size 64 x 64
images = rng.integers(0, 256, size=(16, 64, 64, 3))

# Calculate the average image across the 16 images
average_image = np.mean(images, axis=0)

# Display the shape of the image batch
print("Batch shape:", images.shape)

# Display the shape of the average image
print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


### D2.Justification

A single RGB image has the shape `(64, 64, 3)`, where 64 represents height, 64 represents width, and 3 represents the RGB color channels. A batch of 16 RGB images has the shape `(16, 64, 64, 3)`, where the first dimension represents the number of images. We use `axis=0` to calculate the average of the corresponding pixels across all 16 images while keeping the height, width, and RGB channels unchanged. Therefore, the resulting average image has the shape `(64, 64, 3)`.

## D3. Debug Model Code

**Question:**  
Consider the following code:

```python
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)

w = np.array([0.5, 1.0, 0.2])  # intended weight vector

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred ** 2)
```
Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.


In [19]:

### 2. Code Cell — Corrected Code
# Program: Debug a linear model and correctly calculate Mean Squared Error
# Create input data with 3 samples and 2 features
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

# Create 2 weights because X has 2 features
w = np.array([0.5, 1.0])

# Define the bias
b = 2.0

# Calculate predictions using matrix multiplication
y_pred = X @ w + b

# Define the actual target values
y_true = np.array([10, 20, 30])

# Calculate Mean Squared Error correctly
mse = np.mean((y_true - y_pred) ** 2)

# Display the predictions
print("Predictions:", y_pred)

# Display the Mean Squared Error
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 244.16666666666666


### D3.Justification

There are two main bugs in the original code. First, `X` has shape `(3, 2)`, so it contains 2 features and the weight vector must therefore have shape `(2,)`, but the original `w` has 3 values and cannot be multiplied with `X`.

Second, the MSE expression is incorrect because of operator precedence. In `y_true - y_pred ** 2`, the power operation is performed first, so it calculates `y_true - (y_pred ** 2)`. The correct MSE formula is `np.mean((y_true - y_pred) ** 2)`, where the prediction error is calculated first and then squared.

# Section E – Bonus / Challenge

**Total Marks: +10**

This section contains optional challenge questions that apply NumPy concepts to more advanced AI/ML data processing tasks.

## E1. Per-Column Min-Max Normalization

**Question:**  
Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns. **[5 marks]**

In [20]:
# Program: Perform per-column Min-Max normalization using NumPy
# Create a 2D feature matrix
X = np.array([[10, 100, 1000],
              [20, 200, 2000],
              [30, 300, 3000],
              [40, 400, 4000]])

# Find the minimum value of each column
column_min = np.min(X, axis=0)

# Find the maximum value of each column
column_max = np.max(X, axis=0)

# Apply Min-Max normalization to each column
X_normalized = (X - column_min) / (column_max - column_min)

# Display the original matrix
print("Original Matrix:")
print(X)

# Display the normalized matrix
print("\nNormalized Matrix:")
print(X_normalized)

Original Matrix:
[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]
 [  40  400 4000]]

Normalized Matrix:
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


### Justification

`np.min(X, axis=0)` and `np.max(X, axis=0)` calculate the minimum and maximum values separately for each column. The Min-Max formula is then applied using NumPy broadcasting, which normalizes every feature independently to the range `[0, 1]`. Since the operation is vectorized, no explicit loops over rows or columns are required.

## E2. Three-Level Score Classification

**Question:**  
Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:

- **Fail** (< 40)
- **Average** (40–70 inclusive)
- **Excellent** (> 70)

**Hint:**  
You may need to nest or combine `np.where()` calls. **[5 marks]**

In [21]:
# Program: Classify exam scores into Fail, Average, and Excellent
# Create a 1D array of exam scores
scores = np.array([25, 39, 40, 55, 70, 71, 85])

# Classify scores using nested np.where() without loops or if/else
classification = np.where(
    scores < 40,
    "Fail",
    np.where(scores <= 70, "Average", "Excellent")
)
# Display the scores and their classifications
print("Scores:", scores)
print("Classification:", classification)

Scores: [25 39 40 55 70 71 85]
Classification: ['Fail' 'Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


### Justification

The nested `np.where()` checks each score against the given conditions. Scores below 40 are classified as `"Fail"`, scores from 40 to 70 are classified as `"Average"`, and scores above 70 are classified as `"Excellent"`. The entire classification is done using one vectorized expression without `if/else` statements or explicit loops.